-- +--------------------------------------------------------------------+
-- | CiviCRM version 5                                                  |
-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC (c) 2004-2019                                |
-- +--------------------------------------------------------------------+
-- | This file is a part of CiviCRM.                                    |
-- |                                                                    |
-- | CiviCRM is free software; you can copy, modify, and distribute it  |
-- | under the terms of the GNU Affero General Public License           |
-- | Version 3, 19 November 2007 and the CiviCRM Licensing Exception.   |
-- |                                                                    |
-- | CiviCRM is distributed in the hope that it will be useful, but     |
-- | WITHOUT ANY WARRANTY; without even the implied warranty of         |
-- | MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.               |
-- | See the GNU Affero General Public License for more details.        |
-- |                                                                    |
-- | You should have received a copy of the GNU Affero General Public   |
-- | License and the CiviCRM Licensing Exception along                  |
-- | with this program; if not, contact CiviCRM LLC                     |
-- | at info[AT]civicrm[DOT]org. If you have questions about the        |
-- | GNU Affero General Public License or the licensing of CiviCRM,     |
-- | see the CiviCRM license FAQ at http://civicrm.org/licensing        |
-- +--------------------------------------------------------------------+
--
-- Generated from drop.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the exisiting tables
-- *
-- *******************************************************/

-- drop custom group for syncing groups
DELETE FROM civicrm_custom_group WHERE name = 'CCA_Group_Settings';
DELETE FROM civicrm_custom_field WHERE name = 'Sync_to_CCA';

-- drop option group for syncing groups
DELETE  FROM civicrm_option_group WHERE name = 'sync_to_cca';

-- drop table that stores information for syncing groups
DROP TABLE IF EXISTS civicrm_cca_group_settings;

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_cca_groups_log`;
DROP TABLE IF EXISTS `civicrm_cca_group_contacts_log`;

SET FOREIGN_KEY_CHECKS=1;
