-- +--------------------------------------------------------------------+
-- | CiviCRM version 5                                                  |
-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC (c) 2004-2019                                |
-- +--------------------------------------------------------------------+
-- | This file is a part of CiviCRM.                                    |
-- |                                                                    |
-- | CiviCRM is free software; you can copy, modify, and distribute it  |
-- | under the terms of the GNU Affero General Public License           |
-- | Version 3, 19 November 2007 and the CiviCRM Licensing Exception.   |
-- |                                                                    |
-- | CiviCRM is distributed in the hope that it will be useful, but     |
-- | WITHOUT ANY WARRANTY; without even the implied warranty of         |
-- | MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.               |
-- | See the GNU Affero General Public License for more details.        |
-- |                                                                    |
-- | You should have received a copy of the GNU Affero General Public   |
-- | License and the CiviCRM Licensing Exception along                  |
-- | with this program; if not, contact CiviCRM LLC                     |
-- | at info[AT]civicrm[DOT]org. If you have questions about the        |
-- | GNU Affero General Public License or the licensing of CiviCRM,     |
-- | see the CiviCRM license FAQ at http://civicrm.org/licensing        |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--


-- +--------------------------------------------------------------------+
-- | CiviCRM version 5                                                  |
-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC (c) 2004-2019                                |
-- +--------------------------------------------------------------------+
-- | This file is a part of CiviCRM.                                    |
-- |                                                                    |
-- | CiviCRM is free software; you can copy, modify, and distribute it  |
-- | under the terms of the GNU Affero General Public License           |
-- | Version 3, 19 November 2007 and the CiviCRM Licensing Exception.   |
-- |                                                                    |
-- | CiviCRM is distributed in the hope that it will be useful, but     |
-- | WITHOUT ANY WARRANTY; without even the implied warranty of         |
-- | MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.               |
-- | See the GNU Affero General Public License for more details.        |
-- |                                                                    |
-- | You should have received a copy of the GNU Affero General Public   |
-- | License and the CiviCRM Licensing Exception along                  |
-- | with this program; if not, contact CiviCRM LLC                     |
-- | at info[AT]civicrm[DOT]org. If you have questions about the        |
-- | GNU Affero General Public License or the licensing of CiviCRM,     |
-- | see the CiviCRM license FAQ at http://civicrm.org/licensing        |
-- +--------------------------------------------------------------------+
--
-- Generated from drop.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the exisiting tables
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_cca_key`;
DROP TABLE IF EXISTS `civicrm_cca_groups_log`;
DROP TABLE IF EXISTS `civicrm_cca_group_contacts_log`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_cca_group_contacts_log
-- *
-- *******************************************************/
CREATE TABLE `civicrm_cca_group_contacts_log` (


     `id` int unsigned NOT NULL AUTO_INCREMENT  ,
     `groupid` int unsigned    COMMENT 'FK to Group',
     `contactid` int unsigned    COMMENT 'FK to Contact',
     `action` varchar(10) NOT NULL   ,
     `createdat` timestamp NOT NULL  DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP  
,
        PRIMARY KEY (`id`)
 
 
,          CONSTRAINT FK_civicrm_cca_group_contacts_log_contactid FOREIGN KEY (`contactid`) REFERENCES `civicrm_contact`(`id`) ON DELETE CASCADE,          CONSTRAINT FK_civicrm_cca_group_contacts_log_groupid FOREIGN KEY (`groupid`) REFERENCES `civicrm_group`(`id`) ON DELETE CASCADE  
)    ;

-- /*******************************************************
-- *
-- * civicrm_cca_groups_log
-- *
-- *******************************************************/
CREATE TABLE `civicrm_cca_groups_log` (


     `id` int unsigned NOT NULL AUTO_INCREMENT  ,
     `groupid` int unsigned    COMMENT 'FK to Group',
     `action` varchar(10) NOT NULL   ,
     `createdat` timestamp NOT NULL  DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP  
,
        PRIMARY KEY (`id`)
 
 
,          CONSTRAINT FK_civicrm_cca_groups_log_groupid FOREIGN KEY (`groupid`) REFERENCES `civicrm_group`(`id`) ON DELETE CASCADE  
)    ;

-- /*******************************************************
-- *
-- * civicrm_cca_key
-- *
-- * CCA authentication
-- *
-- *******************************************************/
CREATE TABLE `civicrm_cca_key` (


     `id` int unsigned NOT NULL AUTO_INCREMENT  COMMENT 'Unique CCAKey ID',
     `contact_id` int unsigned NOT NULL   COMMENT 'FK to Contact',
     `hash` varchar(32)    COMMENT 'The hash for checksum',
     `date` timestamp NOT NULL  DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP  
,
        PRIMARY KEY (`id`)
 
 
,          CONSTRAINT FK_civicrm_cca_key_contact_id FOREIGN KEY (`contact_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE CASCADE  
)    ;

 
